### ISSUE TITLE
Use object hash as a key instead of UUID?

### ISSUE THREAD

**Issue by giovannipizzi** [giovannipizzi/disk-objectstore#23]
This could even be an option, and one could even decide the algorithm and store it in the config.json.

Pros: 
- As discussed in 409bc82d2b5c696b845e4819bbc8919cdcb94804, in the end the time to compute the hash seems really small (compared to disk read/write speeds, and also the time to compute a hash of a very small object compared to the time to compute a single UUID).
- It allows implicitly to take care of deduplication of data.

Cons:
- I can get the object key (the hash) only after having processed the whole object. This maybe, however, is not a big deal (but it might/will be e.g. if we want to compress directly to packs, as we don't know in which pack to write until everything is written out).
- One needs to be much more careful to concurrency issues. For instance: if I add an object, now I just know it will be a new UUID, so I just store on disk as a new object. Also, I know from the very beginning where to store it if I want to write directly to packs (I can create the UUID beforehand).  Instead, with SHA1, I need first to check *both* packed and loose objects to see if and object with the same SHA1 is there. And this is fragile, because after the check another process might store another object with the same SHA1.
  - For loose objects, one might decide to ignore if one finds an object already there with the same hash
  - When packing, I might be ok if there is already a packed object with the same hash - then I just delete the loose object.
  - One needs to decide if the best packing strategy is based on the starting characters of the SHA1. In the end, maybe it's not needed! One could store randomly in any of the 256 packs, and anyway we have a single SQLite index. Then we can just add another column saying in which pack the object is sitting (and then one can just store directly to packs to any random pack, and then store this into the pack index).

**Comment by dev-zero** [comment]
> Cons:
> 
>     * I can get the object key (the hash) only after having processed the whole object. This maybe, however, is not a big deal (but it might/will be e.g. if we want to compress directly to packs, as we don't know in which pack to write until everything is written out).

You likely want to to stream into a temporary (CoW semantics) anyway to get more stable recovery from intermittent failures.

>       * One needs to decide if the best packing strategy is based on the starting characters of the SHA1.

Diffusion/confusion properties of cryptographic hashes should give you that, if that's what you mean.

> In the end, maybe it's not needed! One could store randomly in any of the 256 packs, and anyway we have a single SQLite index. Then we can just add another column saying in which pack the object is sitting (and then one can just store directly to packs to any random pack, and then store this into the pack index).

If the database grows really big I'm not sure whether it is a good idea to limit the number of packs. While an algorithm like rsync can figure out what has changed in a pack, it is still much faster if it can only look at size, mtime and name to determine whether to copy the file (0 reads needed vs. having to read the whole file from source).

**Comment by giovannipizzi** [comment]
> You likely want to to stream into a temporary (CoW semantics) anyway to get more stable recovery from intermittent failures.

Just to be sure, does this mean (as I am doing now) to write to a temporary file and then move it? I agree in this case there is no problem, and I just need to declare in the API that the object key can only be retrieved after complete transfer.
As I mentioned, though, this might be a problem when writing directly to packs, with the current logic that determines the pack based on the starting characters of the hash (and I agree this is not really a strong requirement, so could be lifted).

> Diffusion/confusion properties of cryptographic hashes should give you that, if that's what you mean.

I'm not sure if I was clear there. Just to be sure, you mean that if we use the starting part of the hash, we know it's randomly distributed? 
What I meant is that currently the file in which to pack is determined by the first characters of the key.
If the key is a UUID, I generate it first, and then I write directly to the correct pack (scenario here: I'm using this format to store the content of the files that will be then embedded into an export file of AiiDA).
If it's a hash (probably exactly because of the confusion and diffusion properties) I don't think I can predict the first two characters until the end. So I need to write to a temporary file first - but the whole point of writing directly to packs is to avoid this step, so if I have millions of tiny files I only have to open a few packs, rather than to open and close many of them, and then reopen them to pack them. A solution is not to base the decision on where to pack on the first characters of the key, see also below.

> If the database grows really big I'm not sure whether it is a good idea to limit the number of packs. While an algorithm like rsync can figure out what has changed in a pack, it is still much faster if it can only look at size, mtime and name to determine whether to copy the file (0 reads needed vs. having to read the whole file from source).

This is a very good point, an indeed I have been thinking to both points (total number of packs, and the fact that once the repository is big, adding a single small object to a pack will require rsync to re-read the whole big file).

Maybe, also as a solution to the problem before, one might decide that:
- one fixed an approximate size each pack should have (e.g. 10GB, let's say);
- one adds to the "next available" pack until the size exceeds the 10GB (note that this is just a hint size, in a sense it's a minimum size before a new pack is created; e.g. if I am at 9.9GB and I add an object of 100GB, with the current logic I would have a pack of 109.9GB at the end, and only then I would start creating a new pack. Maybe it's ok, though, as anyway there is the possibility that a single object, even compressed, is larger than the target size)
- there is no limit on the number of packs (but with the target size, even on a 20TB partition, one shouldn't get more than ~20000 files).
- at this point, instead of using two-character pack names, I would probably use just a progressive integer? And store this as an additional column in the DB (`pack_file` or something like that). This shouldn't be a big problem as anyway only one process at a time is allowed to pack or write directly to packs, so there should be no risk that two processes try to create the *next* pack at the same time.

BTW, in this case I could actually use the hash as a key, and write to the next available pack, with the caveat that (if we write directly to packs) the byte stream could be added, but then not referenced in the DB if an object with the same hash is in the container already. And one would need, at the end, to do a repack.

Actually, thinking to it, since a single process is writing, maybe one could do the following procedure (do you feel it's ok?)
- append the bytes, possibly compressed, while computing the hash at the same time
- at the end, get the hash
- check if the hash exists already
- if this is the case, go back (with `.seek()`) to the position where you started to write this new object, and [truncate it](https://docs.python.org/3/library/io.html#io.IOBase.truncate).
- continue with the next objects
Possibly this would be fast even for many small objects being written on the same pack file?

Does all the discussions above make sense? :-)

**Comment by dev-zero** [comment]
> > You likely want to to stream into a temporary (CoW semantics) anyway to get more stable recovery from intermittent failures.
> 
> Just to be sure, does this mean (as I am doing now) to write to a temporary file and then move it? I agree in this case there is no problem, and I just need to declare in the API that the object key can only be retrieved after complete transfer.

Exactly.

> As I mentioned, though, this might be a problem when writing directly to packs, with the current logic that determines the pack based on the starting characters of the hash (and I agree this is not really a strong requirement, so could be lifted).

Ah, I see. After some reflecting, I am not sure that writing directly to packs is a good idea:

* seeking into a huge file could potentially cost time, depending on filesystem (especially remote mounted ones, modern local FS should be fine though)
* power-outage during write: not too long ago some filesystems left you with truncated files, which in this case would mean a complete pack truncated (see also how PostgreSQL does storage organization)
* filesystems doing CoW could give some more headaches here in terms of latency, but I'm not sure how they exactly behave
* when receiving multiple streams you could profit from SSDs and multiqueues by receiving them in parallel, which doesn't work when you're writing to a sequential resource (also, on a Fibre-channel a single writer is usually limited, but the system scales well with multiple writers)
* given the points how disaster recovery works, you could get interrupted due to finding extra bytes (unless you simply position and start writing)
* another point: it might be beneficial (not sure yet though), to put beginnings of files onto pagesize boundaries to allow for more efficient memory mapped operations (which speeds up read access tremendously (see [my mmap-based XYZ parser](https://github.com/dev-zero/cp2k-tools/blob/develop/cp2k_tools/parser/xyz.py) allowing to operate on huge trajectories with Python).

> > Diffusion/confusion properties of cryptographic hashes should give you that, if that's what you mean.
> 
> I'm not sure if I was clear there. Just to be sure, you mean that if we use the starting part of the hash, we know it's randomly distributed?

Yes.

> What I meant is that currently the file in which to pack is determined by the first characters of the key.
> If the key is a UUID, I generate it first, and then I write directly to the correct pack (scenario here: I'm using this format to store the content of the files that will be then embedded into an export file of AiiDA).
> If it's a hash (probably exactly because of the confusion and diffusion properties) I don't think I can predict the first two characters until the end.

I see. No, you can't.

> So I need to write to a temporary file first - but the whole point of writing directly to packs is to avoid this step, so if I have millions of tiny files I only have to open a few packs, rather than to open and close many of them, and then reopen them to pack them. A solution is not to base the decision on where to pack on the first characters of the key, see also below.
> 
> > If the database grows really big I'm not sure whether it is a good idea to limit the number of packs. While an algorithm like rsync can figure out what has changed in a pack, it is still much faster if it can only look at size, mtime and name to determine whether to copy the file (0 reads needed vs. having to read the whole file from source).
> 
> This is a very good point, an indeed I have been thinking to both points (total number of packs, and the fact that once the repository is big, adding a single small object to a pack will require rsync to re-read the whole big file).
> 
> Maybe, also as a solution to the problem before, one might decide that:
> 
>     * one fixed an approximate size each pack should have (e.g. 10GB, let's say);

I'd probably go for the 32bit limit here, but maybe there's a better one.

>     * one adds to the "next available" pack until the size exceeds the 10GB (note that this is just a hint size, in a sense it's a minimum size before a new pack is created; e.g. if I am at 9.9GB and I add an object of 100GB, with the current logic I would have a pack of 109.9GB at the end, and only then I would start creating a new pack. Maybe it's ok, though, as anyway there is the possibility that a single object, even compressed, is larger than the target size)
> 
>     * there is no limit on the number of packs (but with the target size, even on a 20TB partition, one shouldn't get more than ~20000 files).
> 
>     * at this point, instead of using two-character pack names, I would probably use just a progressive integer? And store this as an additional column in the DB (`pack_file` or something like that). This shouldn't be a big problem as anyway only one process at a time is allowed to pack or write directly to packs, so there should be no risk that two processes try to create the _next_ pack at the same time.
> 
> 
> BTW, in this case I could actually use the hash as a key, and write to the next available pack, with the caveat that (if we write directly to packs) the byte stream could be added, but then not referenced in the DB if an object with the same hash is in the container already. And one would need, at the end, to do a repack.
> 
> Actually, thinking to it, since a single process is writing, maybe one could do the following procedure (do you feel it's ok?)
> 
>     * append the bytes, possibly compressed, while computing the hash at the same time
> 
>     * at the end, get the hash
> 
>     * check if the hash exists already
> 
>     * if this is the case, go back (with `.seek()`) to the position where you started to write this new object, and [truncate it](https://docs.python.org/3/library/io.html#io.IOBase.truncate).
> 
>     * continue with the next objects
>       Possibly this would be fast even for many small objects being written on the same pack file?
> 
> 
> Does all the discussions above make sense? :-)

Ok, yes. But I have to think about it a bit more :-)

**Comment by giovannipizzi** [comment]
Just [a link for myself](https://stackoverflow.com/questions/28159071/why-doesnt-git-use-more-modern-sha) pointing to other discussions on GIT, mentioning reasons to pick SHA256 over other similar hashes
