### ISSUE TITLE
Implement object deletion

### ISSUE THREAD

**Issue by giovannipizzi** [giovannipizzi/disk-objectstore#5]
This would delete the object directly if loose, or just do a soft delete if packed (deleting from the DB).

As such, it needs to be a `maintenance` operation, see also comments in #6 

To check if it is easy to perform it while the daemons are running.
Otherwise this needs to become a second type of 'stronger' maintenance operation, that can be run only when no-one is even reading the container.

**Comment by sphuber** [comment]
I am not sure where we discussed this anymore, but despite for the majority of operations in `aiida-core` we want to do a soft delete, it would still be good to have a `delete_object` method on the `Container` class. In the front end layer, I will just maintain an internal mapping that is persisted to AiiDA's database, so I will perform a soft delete there with respect to the repository backend in most cases, meaning I won't even call `Container.delete_object`. But for testing and actual maintenance operations, it may sometimes be necessary to have this method.

**Comment by giovannipizzi** [comment]
Indeed, that's definitely in the plans soon. I just wanted to finish understanding some issues of concurrency, because having a robust design depends on how I'll need to tackle those. I think I fixed the issues with Mac OS. Windows is still not fully resolved yet (because the logic of file locking in Windows and POSIX is *very* different...)
