### ISSUE TITLE
Add `mode` property to `PackedObjectReader`

### ISSUE THREAD

**Issue by sphuber** [giovannipizzi/disk-objectstore#57]
Not all clients may always be able to resort to duck-typing and may want to or have to explicitly check. Adding it would be trivial:
```
    @property
    def mode(self):
        return self._fhandle.mode
```

**Comment by giovannipizzi** [comment]
Agreed, this is very easy to add, I just didn't do it.

Feel free to assign to yourself if you want to make a PR (with a simple test to ensure full coverage), otherwise I'll do it

**Comment by sphuber** [comment]
Happy to do it, already have the code locally anyway. But I don't have rights to assign people or add labels etc.
