### ISSUE TITLE
Add method to export a list of hash keys to a new container

### ISSUE THREAD

**Issue by giovannipizzi** [giovannipizzi/disk-objectstore#64]
The API could be `export_to_container(new_container, hashkeys, directly_to_packs=True, max_memory_usage=512*1024*1024)`

This could implement efficient ways to move from one to the other, by limiting the memory usage.
See for instance [this implementation](https://github.com/giovannipizzi/aiida-repository/blob/e1eeaf21d67bee4749f01e6ac1e1e49b2d0b03a0/example_repository.py#L96)

**Comment by giovannipizzi** [comment]
@sphuber I just wanted to know if you have already a version of this or if you want me to write it

**Comment by sphuber** [comment]
No, just an ad-hoc solution for now, for example in the import, I collect all hashkeys from the node metadata and then do something like:
```
with container_export.get_objects_stream_and_meta(hashkeys=set(all_hashkeys)) as triplets:
     for _, stream, _ in triplets:
         container_profile.add_streamed_objects_to_pack([stream])
```
which is probably not very efficient.
Plus getting the hashkeys from the container Sqlite may be a lot fast as well for biggern export files
