### ISSUE TITLE
How to deal with backwards incompatiblity of `is_initialized`

### ISSUE THREAD

**Issue by sphuber** [giovannipizzi/disk-objectstore#86]
Commit 4dff7e849d0e7f469ef75448273b7396475f4ea4 changed the basic content of an initialized `Container` and so also adjusted the logic of `is_initialized`. This breaks existing containers, because due to the addition of the `duplicates` folder, `is_initialized` will return `False` since the `duplicates` does not exist, but then `initialize` will fail, since it *does* contain the rest of the folder. This breaks the paradigm:
```
if not container.is_initialized:
    container.initialize()
```
for existing containers. Since this software is still in alpha, such a break is maybe acceptable, but this might occur again in the future and we need to think how to deal with these situations in the future.

**Comment by giovannipizzi** [comment]
I know, I decided at this phase of development this was acceptable
you just need to create a `duplicates` folder in the repo.

I agree that this should not happen in the future

**Comment by sphuber** [comment]
OK, then it is fine to close this.
